### ISSUE TITLE
release action error，without gpg key

### ISSUE THREAD

**Issue by naah69** [quarkiverse/quarkus-sa-token#20]
@gastaldi Hi，i wanna release 1.0.0, but it need gpg key,can u help me to reslove it ?

https://github.com/quarkiverse/quarkus-sa-token/runs/7175453288?check_suite_focus=true

**Comment by gastaldi** [comment]
@naah69 you need to create the PR from a branch in this repository (not from a forked repository): see https://github.com/quarkiverse/quarkiverse/wiki/Release#important

**Comment by naah69** [comment]
@gastaldi thank you ,i will try it

**Comment by naah69** [comment]
it had released
